tardis_config_version:
  property_type: string
  default: None
  mandatory: True
  help: Version of the configuration file


supernova:
    luminosity_requested:
        property_type: quantity
        mandatory: True
        default: 1 solLum
        help: requested output luminosity for simulation

    time_explosion:
        property_type: quantity
        mandatory: True
        default: None
        help: time since explosion

    distance:
        property_type: quantity
        mandatory: False
        default: None
        help: distance to supernova

    luminosity_wavelength_start:
        property_type: quantity
        mandatory: False
        default: 0 angstrom
        help: start of the integral needed for getting the luminosity right


    luminosity_wavelength_end:
        property_type: quantity
        mandatory: False
        default: inf angstrom
        help: start of the integral needed for getting the luminosity right

atom_data:
    property_type: string
    file: True
    mandatory: True
    help: path or filename to the Atomic Data HDF5 file

plasma:
    initial_t_inner:
        property_type: quantity
        mandatory: False
        default: -1 K
        help: >
            initial temperature of the inner boundary black body. If set to -1 K
            will result in automatic calculation of boundary


    initial_t_rad:
        property_type: quantity
        mandatory: False
        default: 10000 K
        help: initial radiative temperature in all cells (if set

    disable_electron_scattering:    
        property_type: bool
        mandatory: False
        default: False
        help: >
            disable electron scattering process in montecarlo part - non-physical only
            for tests

    ionization:
        property_type: string
        mandatory: True
        default: None
        allowed_value: ['nebular', 'lte']
        help: ionization treatment mode


    excitation:
        property_type: string
        mandatory: True
        default: None
        allowed_value: ['lte', 'dilute-lte']
        help: excitation treatment mode

    radiative_rates_type:
        property_type: string
        mandatory: True
        default: None
        allowed_value: ['dilute-blackbody', 'detailed']
        help: radiative rates treatment mode

    line_interaction_type:
        property_type: string
        mandatory: True
        default: None
        allowed_value: ['scatter', 'downbranch', 'macroatom']
        help: line interaction mode

    w_epsilon:
        property_type: float
        mandatory: False
        default:  1e-10
        help: w to use when j_blues get numerically 0. - avoids numerical complications

    delta_treatment:
        property_type: float
        mandatory: False
        default: None
        help: >
            In the saha calculation set delta equals to the number given in
            this configuration item. if set to None (default), normal delta
            treatment (as described in Mazzali & Lucy 1993) will be applied




montecarlo:
    seed:
        property_type: int
        default: 23111963
        mandatory: False
        help: Seed for the random number generator

    no_of_packets:
        property_type: int
        default: None
        mandatory: True
        help: Seed for the random number generator

    iterations:
        property_type: int
        default: None
        mandatory: True
        help: Number of maximum iterations

    black_body_sampling:
        property_type: quantity_range_sampled
        default: [50 angstrom, 200000 angstrom, 1000000]
        mandatory: False
        help: Sampling of the black-body for energy packet creation (giving maximum and minimum packet frequency)

    last_no_of_packets:
        property_type: int
        default: -1
        mandatory: False
        help: >
            This can set the number of packets for the last run.
            If set negative it will remain the same as all other runs.

    no_of_virtual_packets:
        property_type: int
        default: 0
        mandatory: False
        help: Setting the number of virtual packets for the last iteration.

    enable_reflective_inner_boundary:
        property_type: bool
        default: False
        mandatory: False
        help: >
            experimental feature to enable a reflective boundary.

    inner_boundary_albedo:
        property_type: float
        default: 0.0
        mandatory: False
        help: albedo of the reflective boundary



spectrum:
    property_type: quantity_range_sampled
    default: None
    mandatory: True
    help: Final spectrum sampling
